updates docksal-configuration

diff --git a/vendor/anrt-tools/docksal-configuration/.docksal/commands/css-compile b/vendor/anrt-tools/docksal-configuration/.docksal/commands/css-compile
--- a/vendor/anrt-tools/docksal-configuration/.docksal/commands/css-compile
+++ b/vendor/anrt-tools/docksal-configuration/.docksal/commands/css-compile
@@ -1,8 +1,9 @@
 #!/usr/bin/env bash
 
-## Compiles SASS to CSS in the theme folder using compass.
+## Run npm in the theme folder to Compile CSS.
 ##
 ## Usage: fin css-compile
+##                   --clean reinstalls dependencies (optional)
 ##
 
 source ${DOCKSAL_PATH}/.docksal/helpers
@@ -12,7 +13,24 @@ check_override $@
 
 cd ${THEME_PATH}
 
-echo-green 'Checking for installed bundles'
-fin exec bundle install
-echo-green 'Compiling CSS'
-fin exec bundle exec compass compile
+# Install npm
+fin exec nvm install
+# Set theme nodeJS version as default.
+fin exec nvm alias default $(cat ./.nvmrc)
+fin exec nvm use
+
+if [[ ! -d "node_modules" || $1 == "--clean" ]]; then
+  echo-yellow "Installing dependencies…"
+  fin exec npm ci
+fi
+if [ -d "node_modules" ]; then
+  echo-green "All set up; ready to compile!"
+fi
+
+fin exec npm run build:css
+
+# Provide useful message if fails
+if [ $? -eq 1 ]; then
+  echo-red "Check theme package.json & see https://knowledge.annertech.com/coding/build-tools/"
+fi
+fin cr
